/**
 * ERP Forge Dev Agent — OpenAPI Spec Generator (stub)
 *
 * Generates a stub openapi.yaml listing all endpoints.
 * A full generator would introspect Route Handler types, but this
 * produces a valid starting document that can be refined.
 */

import type { GeneratorContext, GeneratedFile } from "../types.js";
import { writePlatformFile } from "../spec-manager.js";

/**
 * Generates a stub openapi.yaml from the list of route files.
 * Satisfies development_standards.documentation_rules.require_openapi_for_all_endpoints.
 *
 * @param ctx - Generator context
 * @param routeFiles - List of generated route handler files
 * @returns The generated OpenAPI file
 */
export function generateOpenApiSpec(
  ctx: GeneratorContext,
  routeFiles: GeneratedFile[]
): GeneratedFile {
  const spec = ctx.spec;
  const paths: string[] = [];

  // Build path entries from route files
  for (const file of routeFiles) {
    const match = file.relativePath.match(/src\/app\/api\/(v1\/.+)\/route\.ts$/);
    if (!match) continue;

    const apiPath = "/" + match[1].replace(/\[id\]/g, "{id}").replace(/\[([^\]]+)\]/g, "{$1}");
    const isIdRoute = apiPath.includes("{id}");
    const isActionRoute = apiPath.split("/").length > 4;

    if (isActionRoute && isIdRoute) {
      paths.push(
        `  ${apiPath}:\n    post:\n      summary: "${file.specIds[0] ?? "Action"}"\n      tags: [actions]\n      security: [{bearerAuth: []}]\n      responses:\n        '200': {description: Success}`
      );
    } else if (isIdRoute) {
      paths.push(
        `  ${apiPath}:\n    get:\n      summary: Get by ID\n      tags: [${apiPath.split("/")[2]}]\n      security: [{bearerAuth: []}]\n      responses:\n        '200': {description: Success}\n        '404': {description: Not found}\n    patch:\n      summary: Update\n      tags: [${apiPath.split("/")[2]}]\n      security: [{bearerAuth: []}]\n      responses:\n        '200': {description: Updated}\n    delete:\n      summary: Delete\n      tags: [${apiPath.split("/")[2]}]\n      security: [{bearerAuth: []}]\n      responses:\n        '204': {description: Deleted}`
      );
    } else {
      paths.push(
        `  ${apiPath}:\n    get:\n      summary: List\n      tags: [${apiPath.split("/")[2]}]\n      security: [{bearerAuth: []}]\n      parameters:\n        - {name: cursor, in: query, schema: {type: string}}\n        - {name: search, in: query, schema: {type: string}}\n      responses:\n        '200': {description: Paginated list}\n    post:\n      summary: Create\n      tags: [${apiPath.split("/")[2]}]\n      security: [{bearerAuth: []}]\n      responses:\n        '201': {description: Created}`
      );
    }
  }

  const content = `openapi: "3.1.0"
info:
  title: "${spec.business_profile.company_name} ERP API"
  version: "${spec.spec_version}"
  description: "Generated by ERP Forge dev agent. Spec: ${spec.spec_id}"

servers:
  - url: "{baseUrl}/api/v1"
    variables:
      baseUrl:
        default: "http://localhost:3000"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
${paths.join("\n")}
`;

  writePlatformFile(ctx.platformDir, "openapi.yaml", content);

  return {
    relativePath: "openapi.yaml",
    content,
    specIds: ["development_standards"],
    generator: "openapi-generator",
  };
}
