/**
 * ERP Forge Dev Agent — Migration Generator
 *
 * Runs drizzle-kit generate to produce SQL migration files,
 * then writes a matching .down.sql rollback file alongside each.
 */

import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";
import type { GeneratorContext, GeneratedFile } from "../../types.js";

/**
 * Runs drizzle-kit generate in the platform directory to create migration files,
 * then generates .down.sql rollback stubs alongside each migration.
 *
 * @param ctx - Generator context with platform directory
 * @returns List of migration files created
 */
export function generateMigrations(ctx: GeneratorContext): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const cwd = ctx.platformDir;

  console.log("  Running drizzle-kit generate...");
  try {
    execSync("npx drizzle-kit generate", {
      cwd,
      stdio: "inherit",
      env: { ...process.env, DATABASE_URL: "postgresql://placeholder:5432/placeholder" },
    });
  } catch (e) {
    console.warn(`  ⚠ drizzle-kit generate failed — schema files may not exist yet. Skipping migrations.`);
    console.warn(`  Run 'npx drizzle-kit generate' manually in ${cwd} after installing dependencies.`);
    return files;
  }

  // Find generated migration files
  const migrationsDir = path.join(cwd, "drizzle", "migrations");
  if (!fs.existsSync(migrationsDir)) return files;

  const sqlFiles = fs
    .readdirSync(migrationsDir)
    .filter((f) => f.endsWith(".sql") && !f.endsWith(".down.sql"));

  for (const sqlFile of sqlFiles) {
    const fullPath = path.join(migrationsDir, sqlFile);
    const content = fs.readFileSync(fullPath, "utf-8");
    files.push({
      relativePath: `drizzle/migrations/${sqlFile}`,
      content,
      specIds: [],
      generator: "migration-generator",
    });

    // Write a .down.sql stub for rollback
    const downFileName = sqlFile.replace(".sql", ".down.sql");
    const downContent = buildDownMigration(sqlFile, content);
    const downPath = path.join(migrationsDir, downFileName);
    fs.writeFileSync(downPath, downContent);
    files.push({
      relativePath: `drizzle/migrations/${downFileName}`,
      content: downContent,
      specIds: [],
      generator: "migration-generator",
    });
  }

  return files;
}

/**
 * Generates a .down.sql rollback stub for a given forward migration.
 * Produces DROP TABLE statements in reverse order from the CREATE TABLE statements.
 *
 * @param migrationName - Name of the migration file (for comments)
 * @param forwardSql - SQL content of the forward migration
 * @returns Rollback SQL content
 */
function buildDownMigration(migrationName: string, forwardSql: string): string {
  // Extract CREATE TABLE names in order, then DROP in reverse
  const createMatches = [...forwardSql.matchAll(/CREATE TABLE[^"]*"([^"]+)"/gi)];
  const tableNames = createMatches.map((m) => m[1]);

  const dropStatements = [...tableNames]
    .reverse()
    .map((name) => `DROP TABLE IF EXISTS "${name}" CASCADE;`)
    .join("\n");

  return `-- Rollback: ${migrationName}
-- Generated by ERP Forge dev agent — review before running in production

${dropStatements || "-- TODO: Add rollback statements for this migration"}
`;
}
