/**
 * Drizzle Database Singleton
 *
 * Follows the same singleton pattern generated by dev-agent for customer
 * platforms (see dev-agent/generators/db/schema-generator.ts).
 *
 * Uses module-level globalThis caching to reuse the connection pool
 * across Next.js hot-reload cycles in development.
 */
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import * as schema from "./schema/index";

const connectionString = process.env.DATABASE_URL;

if (!connectionString) {
  throw new Error(
    "DATABASE_URL environment variable is not set. " +
      "Add it to .env.local for local development, or configure the Railway Postgres plugin."
  );
}

// Reuse the connection pool across hot-reload in development.
const globalForDb = globalThis as unknown as {
  _erpforgePgClient?: ReturnType<typeof postgres>;
};

const pgClient =
  globalForDb._erpforgePgClient ??
  postgres(connectionString, {
    max: 10,
    idle_timeout: 20,
    connect_timeout: 10,
  });

if (process.env.NODE_ENV !== "production") {
  globalForDb._erpforgePgClient = pgClient;
}

export const db = drizzle(pgClient, { schema });
export type DB = typeof db;

// Re-export schema for convenience in routes and services.
export * from "./schema/index";
